-- =====================================================================
-- FAZA 2 — PROJEKTI
-- Pokreni jednom u Supabase SQL editoru. Skripta je idempotentna:
-- može da se pokrene više puta bez štete.
--
-- Supabase SQL editor vrti ceo fajl kao jednu transakciju — ako bilo šta
-- pukne, ništa se ne primeni. Nema polovičnog stanja.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Čišćenje ostatka stare šeme.
-- U bazi je zatečena tabela projekat_okovi iz starog kalkulatora, bez
-- kolone korisnik_id — Filip je potvrdio da je prazna. Briše se samo taj
-- stari oblik: uslov je da nema korisnik_id, pa ponovno pokretanje ove
-- skripte kasnije NE dira tabelu koju pravimo ispod.
-- ---------------------------------------------------------------------
do $$
begin
  if to_regclass('public.projekat_okovi') is not null
     and not exists (
       select 1 from information_schema.columns
       where table_schema = 'public'
         and table_name = 'projekat_okovi'
         and column_name = 'korisnik_id')
  then
    drop table public.projekat_okovi cascade;
  end if;
end $$;

-- ---------------------------------------------------------------------
-- projekti — tabela možda već postoji iz prve šeme, pravimo je samo ako fali
-- ---------------------------------------------------------------------
do $$
begin
  if to_regclass('public.projekti') is null then
    create table public.projekti (
      id           bigint generated by default as identity primary key,
      korisnik_id  uuid not null default auth.uid() references auth.users(id) on delete cascade,
      naziv        text not null,
      status       text not null default 'na_cekanju',
      napravljen   timestamptz not null default now()
    );
    alter table public.projekti enable row level security;
    create policy "projekti su moji" on public.projekti
      for all using (korisnik_id = auth.uid()) with check (korisnik_id = auth.uid());
  end if;
end $$;

-- dopune — dodaju se samo ako fale, postojeće kolone se ne diraju
alter table public.projekti add column if not exists klijent        text;
alter table public.projekti add column if not exists telefon        text;
alter table public.projekti add column if not exists adresa         text;
alter table public.projekti add column if not exists napomena       text;
alter table public.projekti add column if not exists rok            date;
alter table public.projekti add column if not exists redosled       int         not null default 0;

-- rad i logistika (tab „Rad")
alter table public.projekti add column if not exists sati           numeric     not null default 0;
alter table public.projekti add column if not exists pomocni_dana   numeric     not null default 0;
alter table public.projekti add column if not exists spratovi       int         not null default 0;
alter table public.projekti add column if not exists kilometri      numeric     not null default 0;
alter table public.projekti add column if not exists dana_smestaj   numeric     not null default 0;

-- cena (tab „Cena") — marza null znači: uzmi podrazumevanu iz profila
alter table public.projekti add column if not exists marza          numeric;
alter table public.projekti add column if not exists popust         numeric     not null default 0;

alter table public.projekti
  drop constraint if exists projekti_status_check;
alter table public.projekti
  add constraint projekti_status_check
  check (status in ('na_cekanju', 'u_izradi', 'zavrseno'));

-- ---------------------------------------------------------------------
-- projekat_elementi — element sačuvan u projektu
-- Dimenzije se ne pamte, pamte se parametri. Delove i cenu svaki put
-- izračuna motor.js, pa element prati aktuelne cene materijala.
-- ---------------------------------------------------------------------
create table if not exists public.projekat_elementi (
  id               bigint generated by default as identity primary key,
  korisnik_id      uuid not null default auth.uid() references auth.users(id) on delete cascade,
  projekat_id      bigint not null references public.projekti(id) on delete cascade,
  naziv            text not null default 'Element',
  prostorija       text,
  redosled         int not null default 0,
  konfiguracija_id bigint references public.konfiguracije(id) on delete set null,
  okov_sarka_id    bigint references public.okovi(id) on delete set null,
  okov_nosac_id    bigint references public.okovi(id) on delete set null,
  okov_nogica_id   bigint references public.okovi(id) on delete set null,
  parametri        jsonb not null default '{}'::jsonb,
  napravljen       timestamptz not null default now()
);
create index if not exists projekat_elementi_projekat_idx on public.projekat_elementi (projekat_id);

-- ---------------------------------------------------------------------
-- projekat_okovi — ručno dodat okov (klizači, ručice, sve što nije auto)
-- ---------------------------------------------------------------------
create table if not exists public.projekat_okovi (
  id          bigint generated by default as identity primary key,
  korisnik_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  projekat_id bigint not null references public.projekti(id) on delete cascade,
  okov_id     bigint not null references public.okovi(id) on delete cascade,
  kolicina    numeric not null default 1,
  napomena    text,
  napravljen  timestamptz not null default now()
);
create index if not exists projekat_okovi_projekat_idx on public.projekat_okovi (projekat_id);

-- ---------------------------------------------------------------------
-- projekat_zadaci — čekliste po projektu
-- ---------------------------------------------------------------------
create table if not exists public.projekat_zadaci (
  id          bigint generated by default as identity primary key,
  korisnik_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  projekat_id bigint not null references public.projekti(id) on delete cascade,
  tekst       text not null,
  gotov       boolean not null default false,
  rok         date,
  redosled    int not null default 0,
  napravljen  timestamptz not null default now()
);
create index if not exists projekat_zadaci_projekat_idx on public.projekat_zadaci (projekat_id);

-- ---------------------------------------------------------------------
-- sabloni — zapamćen element koji se ubacuje u bilo koji projekat
-- ---------------------------------------------------------------------
create table if not exists public.sabloni (
  id               bigint generated by default as identity primary key,
  korisnik_id      uuid not null default auth.uid() references auth.users(id) on delete cascade,
  naziv            text not null,
  konfiguracija_id bigint references public.konfiguracije(id) on delete set null,
  okov_sarka_id    bigint references public.okovi(id) on delete set null,
  okov_nosac_id    bigint references public.okovi(id) on delete set null,
  okov_nogica_id   bigint references public.okovi(id) on delete set null,
  parametri        jsonb not null default '{}'::jsonb,
  napravljen       timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- RLS — svako vidi samo svoje
--
-- Prvo osiguranje: ako je neka od ovih tabela zatečena iz stare šeme bez
-- kolone korisnik_id, dodaj je pre nego što politika krene da je traži.
-- Kolona namerno nije NOT NULL — postojeći redovi bi pali na toj proveri,
-- a ovako ih politika prosto ne prikazuje nikome dok im se ne upiše vlasnik.
-- ---------------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array['projekat_elementi', 'projekat_okovi', 'projekat_zadaci', 'sabloni']
  loop
    execute format(
      'alter table public.%I add column if not exists korisnik_id uuid
         default auth.uid() references auth.users(id) on delete cascade', t);
  end loop;
end $$;

do $$
declare t text;
begin
  foreach t in array array['projekat_elementi', 'projekat_okovi', 'projekat_zadaci', 'sabloni']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "%s su moji" on public.%I', t, t);
    execute format(
      'create policy "%s su moji" on public.%I for all
         using (korisnik_id = auth.uid()) with check (korisnik_id = auth.uid())', t, t);
  end loop;
end $$;
